In [1]:
import numpy as np
from pathlib import Path

In [2]:
GRAYSCALE_IMAGES_PATH = Path(".")

In [5]:
image_0 = np.array(range(0, 256, 32)).reshape((2, 2, 2))
np.save(GRAYSCALE_IMAGES_PATH / "image_0_2x2x2.npy", image_0)
print(image_0)

[[[  0  32]
  [ 64  96]]

 [[128 160]
  [192 224]]]


In [6]:
np.random.seed(42)
image_1= np.random.randint(0, 256, size=(2, 2, 2), dtype=np.uint8)
np.save(GRAYSCALE_IMAGES_PATH / "image_1_2x2x2.npy", image_1)
print(image_1)

[[[102 220]
  [225  95]]

 [[179  61]
  [234 203]]]
